name: "Squire.js test"

on: [push]

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        run: docker run --rm -v $(PWD):/opt -w /opt giovannic/squire bash -c "npm install && npm run build && npm run test && npm run e2e"
